### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by bookaneers** [bookaneers/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create a gray background for the entire screen
- [x] limited the screen to max-width: 992px
- [x] add a formula indy look-like car on the top right corner
