### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by bookaneers** [bookaneers/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] user will be able to turn car to the right
- [x] user will be able to turn car to the left
- [x] user will be able to turn car all the way around
