### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by bookaneers** [bookaneers/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] user will be able to turn right
- [x] user will be able to turn left
- [x] user will be able to stop the car in any direction
